FROM docker.io/library/debian:trixie-slim
RUN apt-get update \
  && apt-get install -y --no-install-recommends ca-certificates wget libgomp1 libcurl4 libvulkan1 mesa-vulkan-drivers \
  && rm -rf /var/lib/apt/lists/*
WORKDIR /opt/matchora
CMD ["/opt/matchora/matchora"]
